#### Import des librairies

In [1]:
import pandas as pd
from tqdm import tqdm
import numpy as np

In [2]:
path_file = '~/Bureau/exports/20241112/AGS_20241112_exports_agronomes_-archive/AGS_20241112_exports_agronomes_assolees_synthetisees.csv'

ENTREPOT_PATH = '~/Bureau/utils/data/'
df = {}

#### Import des données

In [4]:
# ------------------ #
# IMPORT DES DONNÉES #
# ------------------ #


def import_df(df_name, path_data, sep, index_col=None):
    df[df_name] = pd.read_csv(path_data+df_name+'.csv', sep = sep, index_col=index_col, low_memory=False).replace({'\r\n': '\n'}, regex=True)

def import_dfs(df_names, path_data, sep = ',', index_col=None, verbose=False):
    for df_name in tqdm(df_names) : 
        if(verbose) :
            print(" - ", df_name)
        import_df(df_name, path_data, sep, index_col=index_col)

tables_with_id = [
    'espece'
]

tables_without_id = [
]

# import des données de l'entrepôt avec la colonne 'id' en index 
import_dfs(tables_with_id, ENTREPOT_PATH, sep = ',', index_col='id', verbose=False)

# import des données du magasin
import_dfs(tables_without_id, ENTREPOT_PATH, sep = ',', verbose=False)

100%|██████████| 1/1 [00:00<00:00, 29.12it/s]
0it [00:00, ?it/s]

In [14]:
df['espece']['libelle_destination_aee']

id
fr.inra.agrosyst.api.entities.referential.RefEspece_0c089690-d856-4559-9e8a-b14887d4be1f          NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_e77063f0-159f-47aa-854e-ba6b93808545          NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_74e549de-66d0-4c54-8283-12fcd850a275          NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_c899e17b-6826-4c10-9c4f-12c7d15889f0          NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_3f17739c-1cd9-4613-9bc7-1380dc174b66          NaN
                                                                                              ...
fr.inra.agrosyst.api.entities.referential.RefEspece_b5286bee-0d73-4c0f-aef6-144b686a9af4          NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_2a01d716-9ff3-470d-a917-fe25efd70e98          NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_cb0328c7-c11c-488b-9a70-f2239d7347ba    Grain(es)
fr.inra.agrosyst.api.entities.referential.RefEspece_b613dffc-a8d2-4e77-8e70-320218916b65          NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_a61f7351-7827-4e67-a2b4-8bb13bc61ae3          NaN
Name: libelle_destination_aee, Length: 892, dtype: object

In [18]:
df['espece']

,code_espece_botanique,code_qualifiant_aee,code_type_saisonnier_aee,code_destination_aee,code_categorie_culture,libelle_categorie_culture,commentaire,libelle_espece_botanique,libelle_qualifiant_aee,libelle_type_saisonnier_aee,...,nom_latin_gnis,id_culture_acta,nom_culture_acta,remarque_culture_acta,typocan_espece,typocan_espece_maraich,typodirodur_espece,typodirodur_espece_precise,typodirodur_espece_famille_bota,typodirodur_espece_periode_semis
id,,,,,,,,,,,,,,,,,,,,,
fr.inra.agrosyst.api.entities.referential.RefEspece_0c089690-d856-4559-9e8a-b14887d4be1f,ZBV,NaN,NaN,NaN,J02,Cultures légumières,NaN,Fraisier,NaN,NaN,...,NaN,200,fraisier,NaN,Fraisier,Fraisier,Fraisier,Fraisier,Rosaceae,pluriannuelle
fr.inra.agrosyst.api.entities.referential.RefEspece_e77063f0-159f-47aa-854e-ba6b93808545,UK2,NaN,NaN,NaN,J10,Grandes cultures,NaN,Tritordeum sp.,NaN,NaN,...,NaN,17,céréales,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_74e549de-66d0-4c54-8283-12fcd850a275,Z98,NaN,NaN,NaN,J05,Divers,NaN,Autres cultures,NaN,NaN,...,NaN,309,cultures diverses,NaN,Autre,Autre,NaN,NaN,NaN,NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_c899e17b-6826-4c10-9c4f-12c7d15889f0,ZBQ,ZLT,NaN,NaN,J07,Cultures fourragères/Prairie/ Pelouse/ Gazon,NaN,Fétuque élevée,permanente,NaN,...,FESTUCA ARUNDINACEA SCHRE,801,fétuque élevée,NaN,Graminée fourragère,Graminée fourragère,Fetuque,Fétuque élevée permanente,Poaceae,pluriannuelle
fr.inra.agrosyst.api.entities.referential.RefEspece_3f17739c-1cd9-4613-9bc7-1380dc174b66,UK3,NaN,NaN,NaN,J03 ou J11,Cultures ornementales/PPAM,NaN,Grande camomille,NaN,NaN,...,NaN,1231,grande camomille (paternelle),NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fr.inra.agrosyst.api.entities.referential.RefEspece_b5286bee-0d73-4c0f-aef6-144b686a9af4,ZEM,NaN,NaN,NaN,J07,Cultures fourragères/Prairie/ Pelouse/ Gazon,NaN,Spergule,NaN,NaN,...,NaN,514,plantes à parfum,aromatiques et médicinales,NaN,NaN,NaN,NaN,NaN,NaN
fr.inra.agrosyst.api.entities.referential.RefEspece_2a01d716-9ff3-470d-a917-fe25efd70e98,ZMC,NaN,NaN,NaN,J07,Cultures fourragères/Prairie/ Pelouse/ Gazon,NaN,Trèfle violet,NaN,NaN,...,TRIFOLIUM PRATENSE L.,43,trèfle violet,NaN,Légumineuse fourragère,Légumineuse fourragère,Trefle,Trèfle violet,Fabaceae,pluriannuelle
fr.inra.agrosyst.api.entities.referential.RefEspece_cb0328c7-c11c-488b-9a70-f2239d7347ba,ZMK,NaN,ZFA,ZLD,J10,Grandes cultures,NaN,Vesce commune,NaN,Printemps,...,VICIA SATIVA L.,374,vesce commune,NaN,Protéagineux,Protéagineux,Vesce,Vesce commune Printemps Grain(es),Fabaceae,printemps
fr.inra.agrosyst.api.entities.referential.RefEspece_b613dffc-a8d2-4e77-8e70-320218916b65,ZBF,NaN,NaN,NaN,J02,Cultures légumières,NaN,Concombre,NaN,NaN,...,CUCUMIS SATIVUS L.,255,concombre,NaN,Légume,Concombre,Concombre,Concombre,Cucurbitaceae,ete
fr.inra.agrosyst.api.entities.referential.RefEspece_a61f7351-7827-4e67-a2b4-8bb13bc61ae3,ZAX,ZMQ,NaN,NaN,J02,Cultures légumières,NaN,Céleri,Branches,NaN,...,APIUM GRAVEOLENS L.,222,céleri branche,NaN,Légume,Céleri Branches,NaN,NaN,NaN,NaN

In [17]:
df['espece'].loc[
   ~df['espece']['libelle_destination_aee'].isna()
][['typodirodur_espece','typodirodur_espece_precise','typodirodur_espece_famille_bota','typodirodur_espece_periode_semis', 'libelle_destination_aee']]

,typodirodur_espece,typodirodur_espece_precise,typodirodur_espece_famille_bota,typodirodur_espece_periode_semis,libelle_destination_aee
id,,,,,
fr.inra.agrosyst.api.entities.referential.RefEspece_13b37dbb-e6f5-4571-8fef-80a8fce54e0b,Prairie,Prairie permanente pâturée,NaN,pluriannuelle,pâturée
fr.inra.agrosyst.api.entities.referential.RefEspece_44fac62b-50a1-4bb4-b249-98a98d7b4a77,Prairie,Prairie permanente fauchée,NaN,pluriannuelle,fauchée
fr.inra.agrosyst.api.entities.referential.RefEspece_2a63a78c-c166-497b-b287-351a58f67c90,Radis,Radis Noir(e) Potager,Brassicaceae,NaN,Potager
fr.inra.agrosyst.api.entities.referential.RefEspece_64b26308-5ba2-41cf-b692-7aab4e71bda5,NaN,NaN,NaN,NaN,Transformation
fr.inra.agrosyst.api.entities.referential.RefEspece_2299f47e-bb3b-4952-bb58-6843819ae91f,NaN,NaN,NaN,NaN,Transformation
...,...,...,...,...,...
fr.inra.agrosyst.api.entities.referential.RefEspece_682ab4b5-9f08-41bb-86cb-d0188a0d0d9d,Pomme de terre,Pomme de terre Consommation transformation,Solanaceae,ete,transformation
fr.inra.agrosyst.api.entities.referential.RefEspece_475167a1-3c85-4cd1-9a08-ad9424101320,Vesce,Vesce à quatre graines Grain(es),Fabaceae,NaN,Grain(es)
fr.inra.agrosyst.api.entities.referential.RefEspece_a946db92-1d4d-4fdb-95bc-471075fba5c6,NaN,NaN,NaN,NaN,Autre
fr.inra.agrosyst.api.entities.referential.RefEspece_c2c419a0-44e0-46f1-b830-74aced37265d,Mais,Maïs amidon,Poaceae,ete,amidon
fr.inra.agrosyst.api.entities.referential.RefEspece_cb0328c7-c11c-488b-9a70-f2239d7347ba,Vesce,Vesce commune Printemps Grain(es),Fabaceae,printemps,Grain(es)

In [24]:
df['test'] = pd.read_csv('~/Bureau/temp/Gcpe_CP_synth_310323 (3)/gcpe_head.csv', engine='python')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 6010: invalid continuation byte

In [8]:
df['assolees_synthetisees']

,domaine_code,domaine_id,domaine_nom,domaine_campagne,sdc_code,sdc_id,sdc_nom,systeme_synthetise_id,systeme_synthetise_nom,systeme_synthetise_campagnes,...,culture_especes_edi,ci_code,ci_nom,precedent_rotation_id,precedent_rang,precedent_indicateur_branche,precedent_code,precedent_nom,precedent_especes_edi,frequence_connexion
0,5cad4015-d842-4edf-b693-286531862638,fr.inra.agrosyst.api.entities.Domain_ef3317ef-...,PETREQUIN Philippe,2019,803e9c96-3df4-4f75-be89-52d7d83fbac0,fr.inra.agrosyst.api.entities.GrowingSystem_24...,Système PP,fr.inra.agrosyst.api.entities.practiced.Practi...,Système PP,2019,...,Colza Oléagineux Hiver,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,7,5,5150add0-d2ec-4ee2-8e36-1a55d2f37139,Féverole d'Hiver,Fèverole Hiver,100.0
1,5cad4015-d842-4edf-b693-286531862638,fr.inra.agrosyst.api.entities.Domain_ef3317ef-...,PETREQUIN Philippe,2019,803e9c96-3df4-4f75-be89-52d7d83fbac0,fr.inra.agrosyst.api.entities.GrowingSystem_24...,Système PP,fr.inra.agrosyst.api.entities.practiced.Practi...,Système PP,2019,...,Blé tendre Hiver Meunier,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,1,1,16f513b6-0a95-4123-b18b-b68c4b7d6bdc,Colza d'Hiver,Colza Oléagineux Hiver,100.0
2,5cad4015-d842-4edf-b693-286531862638,fr.inra.agrosyst.api.entities.Domain_ef3317ef-...,PETREQUIN Philippe,2019,803e9c96-3df4-4f75-be89-52d7d83fbac0,fr.inra.agrosyst.api.entities.GrowingSystem_24...,Système PP,fr.inra.agrosyst.api.entities.practiced.Practi...,Système PP,2019,...,Sorgho Grain(es),e4881065-ddcc-4de1-b0e4-b7f8909f412d,Avoine/Vesce,fr.inra.agrosyst.api.entities.practiced.Practi...,2,1,a29ac944-d770-4a86-9219-e26b335ec615,Blé tendre d'Hiver,Blé tendre Hiver Meunier,50.0
3,5cad4015-d842-4edf-b693-286531862638,fr.inra.agrosyst.api.entities.Domain_ef3317ef-...,PETREQUIN Philippe,2019,803e9c96-3df4-4f75-be89-52d7d83fbac0,fr.inra.agrosyst.api.entities.GrowingSystem_24...,Système PP,fr.inra.agrosyst.api.entities.practiced.Practi...,Système PP,2019,...,Orge 2 rangs Hiver,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,2,1,a29ac944-d770-4a86-9219-e26b335ec615,Blé tendre d'Hiver,Blé tendre Hiver Meunier,50.0
4,5cad4015-d842-4edf-b693-286531862638,fr.inra.agrosyst.api.entities.Domain_ef3317ef-...,PETREQUIN Philippe,2019,803e9c96-3df4-4f75-be89-52d7d83fbac0,fr.inra.agrosyst.api.entities.GrowingSystem_24...,Système PP,fr.inra.agrosyst.api.entities.practiced.Practi...,Système PP,2019,...,Soja,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,3,1,a00662fc-68b0-4801-9362-2bd047aae17e,Sorgho,Sorgho Grain(es),100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95648,0b38046a-497a-42ce-bcfd-f37bda73724d,fr.inra.agrosyst.api.entities.Domain_aa954610-...,Ferme_LEG_ADIDA Montchabrol,2016,d5f659ab-7aa3-431b-8c80-2778ae0e1998,fr.inra.agrosyst.api.entities.GrowingSystem_c5...,LGF32343_AB_TU,fr.inra.agrosyst.api.entities.practiced.Practi...,PTZ0 - ADIDA TUL,2016,...,Framboisier,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,3,1,75c1d4ee-2419-4b28-a143-65a53c9ba34c,FRAMBOISIER,Framboisier,100.0
95649,4d75fbf4-3dde-4031-be4d-3b0eb96f788b,fr.inra.agrosyst.api.entities.Domain_b2967110-...,Ferme_LEG_COURNIL,2013,ea754aec-5718-4c0f-a806-f71746c75932,fr.inra.agrosyst.api.entities.GrowingSystem_e6...,LGF26078 - COURNIL,fr.inra.agrosyst.api.entities.practiced.Practi...,Synthétisé_LGF26078_Cournil_2013,2013,...,Framboisier,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,4,5,6bbe35e3-6c96-4779-bb1c-0b07bbb01c4e,Framboisier remontant 2 rang - 1ere année,Framboisier,100.0
95650,4d75fbf4-3dde-4031-be4d-3b0eb96f788b,fr.inra.agrosyst.api.entities.Domain_b2967110-...,Ferme_LEG_COURNIL,2013,ea754aec-5718-4c0f-a806-f71746c75932,fr.inra.agrosyst.api.entities.GrowingSystem_e6...,LGF26078 - COURNIL,fr.inra.agrosyst.api.entities.practiced.Practi...,Synthétisé_LGF26078_Cournil_2013,2013,...,Framboisier remontant,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,1,1,6bbe35e3-6c96-4779-bb1c-0b07bbb01c4e,Framboisier remontant 2 rang - 1ere année,Framboisier,100.0
95651,4d75fbf4-3dde-4031-be4d-3b0eb96f788b,fr.inra.agrosyst.api.entities.Domain_b2967110-...,Ferme_LEG_COURNIL,2013,ea754aec-5718-4c0f-a806-f71746c75932,fr.inra.agrosyst.api.entities.GrowingSystem_e6...,LGF26078 - COURNIL,fr.inra.agrosyst.api.entities.practiced.Practi...,Synthétisé_LGF26078_Cournil_2013,2013,...,Framboisier remontant,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,2,1,10692eb4-145c-44d4-8e9d-893f75d40e36,Framboisier remontant 2 rangs double prod,Framboisier remontant,100.0
95652,4d75fbf4-3dde-4031-be4d-3b0eb96f788b,fr.inra.agrosyst.api.entities.Domain_b2967110-...,Ferme_LEG_COURNIL,2013,ea754aec-5718-4c0f-a806-f71746c75932,fr.inra.agrosyst.api.entities.GrowingSystem_e6...,LGF26078 - COURNIL,fr.inra.agrosyst.api.entities.practiced.Practi...,Synthétisé_LGF26078_Cournil_2013,2013,...,Framboisier,NaN,NaN,fr.inra.agrosyst.api.entities.practiced.Practi...,3,4,10692eb4-145c-44d4-8e9d-893f75d40e36,Framboisier remontant 2 rangs double prod,Framboisier remontant,100.0

In [28]:
# on ne sélectionne que les traitements de semences
df['traitement_semence'] = df['intrant'].loc[
    df['intrant']['type'] == 'TRAITEMENT_SEMENCE'
].reset_index()

In [80]:
# on ajoute au traitement de semence l'information du lot dans lequel il est et du composant de culture sur lequel il porte
left = df['traitement_semence']
right = df['semence'][['lot_semence_id', 'composant_culture_id']]
df['traitement_semence_extanded'] = pd.merge(left, right, left_on='semence_id', right_index=True, how='left')

In [88]:
# on groupe par lot_semenbce_id et ref_nom pour obtenir l'occurrence d'un même traitement dans un lot de semence
df['meme_traitement_dans_lot'] = df['traitement_semence_extanded'].groupby(['lot_semence_id', 'composant_culture_id', 'ref_id']).agg({
    'id' : 'count'
}).reset_index().rename(columns={'id' : 'nombre'})

In [89]:
# on ne garde que ceux qui sont à priori problématiques
df['lot_semence_problematiques'] = df['meme_traitement_dans_lot'].loc[
    df['meme_traitement_dans_lot']['nombre'] > 1
]

In [90]:
# on rajoute les information contextuelles pour vérifier sur l'interface : 
left = df['lot_semence_problematiques']
right = df['intrant'][['domaine_id', 'nom_utilisateur']]
merge = pd.merge(left, right, left_on='lot_semence_id', right_index=True, how='left')

In [91]:
merge

,lot_semence_id,composant_culture_id,ref_id,nombre,domaine_id,nom_utilisateur
3,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_885a3a37-...,"Maïs ensilage, Mais (Volney) Semences certifié..."
240,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_7e22249e-...,Blé tendre Blé tendre (Providence)
309,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_ca957e5b-...,Orge Orge (Laverda)
508,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_ff151283-...,Blé tendre Blé tendre (Chevignon)
682,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_8dbaaac9-...,MAIS ENSILAGE Maïs
...,...,...,...,...,...,...
20448,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_3d78867b-...,Blé tendre Blé tendre (CHRISTOPH)
20613,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_496ff380-...,Orge d'hiver Orge (Amistar)
20643,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_4f694478-...,Blé tendre Blé tendre (Nemo)
20693,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_cc5ad288-...,Blé tendre Blé tendre (Providence)
20759,fr.inra.agrosyst.api.entities.DomainSeedLotInp...,fr.inra.agrosyst.api.entities.CroppingPlanSpec...,fr.inra.agrosyst.api.entities.referential.RefA...,2,fr.inra.agrosyst.api.entities.Domain_fae9bafb-...,"Blé tendre Blé tendre (Talendor), Blé tendre (..."

In [11]:
studied_ids = ['fr.inra.agrosyst.api.entities.effective.EffectiveIntervention_69a3d219-a1b2-4d8f-9a84-4f0edfa54318']

In [12]:
left = df['intervention_realise']
right = df['intervention_realise_agrege']
df['intervention_realise_extanded'] = pd.merge(left, right, left_index=True, right_index=True, how='left')

KeyError: 'intervention_realise'

In [ ]:
df['intervention_realise_extanded'].loc[
    df['intervention_realise_extanded'].index.isin(studied_ids)
]

,nom,type,commentaire,date_debut,date_fin,freq_spatiale,nombre_de_passage,psci,psci_phyto_avec_amm,psci_phyto_sans_amm,...,culture_id,dispositif_id,domaine_id,noeuds_realise_id_y,parcelle_id,plantation_perenne_phases_realise_id_y,plantation_perenne_realise_id,sdc_campagne,sdc_id,zone_id
id,,,,,,,,,,,,,,,,,,,,,
fr.inra.agrosyst.api.entities.effective.EffectiveIntervention_69a3d219-a1b2-4d8f-9a84-4f0edfa54318,Intrant,SEMIS,NaN,2022-10-28,2022-10-28,0.710983,1,0.710983,0.710983,NaN,...,fr.inra.agrosyst.api.entities.CroppingPlanEntr...,fr.inra.agrosyst.api.entities.GrowingPlan_9e90...,fr.inra.agrosyst.api.entities.Domain_3623f0c3-...,fr.inra.agrosyst.api.entities.effective.Effect...,fr.inra.agrosyst.api.entities.Plot_c1068983-92...,NaN,NaN,2023.0,fr.inra.agrosyst.api.entities.GrowingSystem_b6...,fr.inra.agrosyst.api.entities.Zone_5728e322-53...

#### Traitement des données