#### Import des librairies

In [ ]:
import pandas as pd
from tqdm import tqdm
import numpy as np

In [ ]:
path_file = '/home/bvuittenez/Bureau/utils/catalogue_script_agrosyst/02_outils/data/external_data/agreste/'

ENTREPOT_PATH = '~/Bureau/utils/data/'
df = {}

In [ ]:
STUDIED_YEAR = 2025
# Attention, Nicolas Chartier suggérait d'utiliser plutôt les tableaux interractifs : https://agreste.agriculture.gouv.fr/agreste-saiku/?plugin=true&query=query/open/SAANR_DEVELOPPE_2#query/open/SAANR_DEVELOPPE_2

DICT_MATCH_AGRESTE_CAN = {
    "01 - Blé tendre d'hiver et épeautre": "null",
    '02 - Blé tendre de printemps': "null",
    '03 - Total blé tendre (01 + 02)':"Blé tendre",
    "04 - Blé dur d'hiver": "null",
    '05 - Blé dur de printemps': "null",
    '06 - Total blé dur (04 + 05)': "Blé dur",
    '07 - Seigle': "null",
    "08 - Orge d'hiver et escourgeon": "null",
    '09 - Orge de printemps': "null",
    '10 - Total orge et escourgeon (08 + 09)': "Orge",
    "11 - Avoine d'hiver": "null",
    '12 - Avoine de printemps': "null",
    '13 - Total avoine (11 + 12)': "somme",
    '14 - Maïs grain irrigué': "Maïs",
    '15 - Maïs grain non irrigué': "Maïs",
    '17 - Maïs semence': "Maïs",
    '18 - Total maïs grain et maïs semence (16 + 17 )': "somme",
    '19 - Sorgho grain': "null",
    '20 - Triticale': "Triticale",
    '21 - Autres céréales non mélangées': "null",
    '22 - Mélanges de céréales': "null",
    '23 - Total céréales (sauf riz) (03 + 06 + 07 + 10 + 13 + 18 + ... + 22)': "somme",
    '24 - Riz indica': "null",
    '25 - Autres riz (Japonica)': "null",
    '26 - Total riz (24 + 25)': "null",
    '27 - Total toutes céréales (23 + 26)': "null",
    '28 - PAILLES': "null",
    "29 - Colza grain d'hiver": "null",
    '30 - Colza grain de printemps et navette': "null",
    '31 - Total colza grain et navette (29 + 30)': "Colza",
    '32 - Tournesol': "Tournesol",
    '33 - Soja': "null",
    '34 - Lin oléagineux': "null",
    '35 - Autres oléagineux (hors chanvre)': "null",
    '36 - Total oléagineux (31 + … + 35)': "somme",
    "37 - Légumes à cosse d'origine tropicale": "null",
    '38 - Féveroles et fèves': "null",
    '39 - Haricots secs (y compris semences)': "null",
    '40 - Lentilles (y compris semences)': "null",
    '41 - Pois protéagineux': "Pois protéagineux",
    '42 - Mélange de pois': "null",
    '43 - Pois chiches (y compris semences)': "null",
    '44 - Lupin doux': "null",
    '45 - Autres protéagineux': "null",
    '46 - Total protéagineux et légumes secs cultivés pour leur graine (37 + … + 45)': "somme"
}


DICT_MATCH_DEPT_ANCIENNE_REGION = {
    '001': 'Picardie',
    '002': 'Nord-Pas-de-Calais',
    '003': 'Picardie',
    '004': 'Nord-Pas-de-Calais',
    '005': 'Nord-Pas-de-Calais',
    '006': 'Alsace',
    '007': 'Auvergne',
    '008': 'Bourgogne',
    '009': 'Bourgogne',
    '010': 'Champagne-Ardenne',
    '011': 'Champagne-Ardenne',
    '012': 'Île-de-France',
    '013': 'Provence-Alpes-Côte d’Azur',
    '014': 'Basse-Normandie',
    '015': 'Auvergne',
    '016': 'Nouvelle-Aquitaine (Bordeaux région)',
    '017': 'Provence-Alpes-Côte d’Azur',
    '018': 'Auvergne',
    '019': 'Bourgogne',
    '02A': 'Corse',
    '02B': 'Corse',
    '020': 'Bourgogne',
    '021': 'Bourgogne',
    '022': 'Picardie',
    '023': 'Auvergne',
    '024': 'Centre-Val de Loire',
    '025': 'Franche-Comté',
    '026': 'Nord-Pas-de-Calais',
    '027': 'Basse-Normandie',
    '028': 'Basse-Normandie',
    '029': 'Bourgogne',
    '030': 'Limousin',
    '031': 'Limousin',
    '032': 'Champagne-Ardenne',
    '033': 'Nouvelle-Aquitaine',
    '034': 'Nouvelle-Aquitaine',
    '035': 'Nouvelle-Aquitaine',
    '036': 'Occitanie',
    '037': 'Nouvelle-Aquitaine',
    '038': 'Nouvelle-Aquitaine',
    '039': 'Franche-Comté',
    '040': 'Auvergne',
    '041': 'Auvergne',
    '042': 'Sud-Est (Rhône-Alpes)',
    '043': 'Auvergne',
    '044': 'Pays de la Loire',
    '045': 'Pays de la Loire',
    '046': 'Pays de la Loire',
    '047': 'Pays de la Loire',
    '048': 'Pays de la Loire',
    '049': 'Nouvelle-Aquitaine',
    '050': 'Basse-Normandie',
    '051': 'Champagne-Ardenne',
    '052': 'Champagne-Ardenne',
    '053': 'Lorraine',
    '054': 'Champagne-Ardenne',
    '055': 'Champagne-Ardenne',
    '056': 'Basse-Normandie',
    '057': 'Picardie',
    '058': 'Nord-Pas-de-Calais',
    '059': 'Nord-Pas-de-Calais',
    '060': 'Picardie',
    '061': 'Haute-Normandie',
    '062': 'Nord-Pas-de-Calais',
    '063': 'Auvergne',
    '064': 'Midi-Pyrénées',
    '065': 'Midi-Pyrénées',
    '066': 'Midi-Pyrénées',
    '067': 'Alsace',
    '068': 'Alsace',
    '069': 'Rhône-Alpes',
    '070': 'Franche-Comté',
    '071': 'Franche-Comté',
    '072': 'Bourgogne',
    '073': 'Auvergne',
    '074': 'Pays de la Loire',
    '075': 'Île-de-France',
    '076': 'Basse-Normandie',
    '077': 'Île-de-France',
    '078': 'Île-de-France',
    '079': 'Provence-Alpes-Côte d’Azur',
    '080': 'Picardie',
    '081': 'Haute-Normandie',
    '082': 'Auvergne',
    '083': 'Provence-Alpes-Côte d’Azur',
    '084': 'Provence-Alpes-Côte d’Azur',
    '085': 'Bourgogne',
    '086': 'Bourgogne',
    '087': 'Auvergne',
    '088': 'Pays de la Loire',
    '089': 'Bourgogne',
    '090': 'Bourgogne-Franche-Comté',  # (Territoire de Belfort était administrativement en Bourgogne avant 2015)
    '091': 'Île-de-France',
    '092': 'Île-de-France',
    '093': 'Île-de-France',
    '094': 'Île-de-France',
    '095': 'Île-de-France',
    '971': 'Guadeloupe (ancienne région)',
    '972': 'Martinique (ancienne région)',
    '973': 'Guyane (ancienne région)',
    '974': 'La Réunion (ancienne région)',
}

In [ ]:
df['surface_culture_departementales_agreste'] = pd.read_csv(path_file+'surface_culture_departementales_agreste.csv')
df['surface_culture_departementales_agreste'] = df['surface_culture_departementales_agreste'].iloc[4:]
df['surface_culture_departementales_agreste'].columns = df['surface_culture_departementales_agreste'].iloc[0].values
df['surface_culture_departementales_agreste'] = df['surface_culture_departementales_agreste'].iloc[1:]
df['surface_culture_departementales_agreste']['numero_departement'] = df['surface_culture_departementales_agreste']['LIB_DEP'].str.split(' - ').apply(lambda x: x[0])

In [ ]:
# création du dataframe permettant d'effectuer le match entre nomenclature Agreste et CAN
df['match_agreste_can'] = pd.DataFrame([DICT_MATCH_AGRESTE_CAN]).T.reset_index().rename(columns={
    0:"nomenclature_can",
    'index' : "nomenclature_agreste"
})

# reclassification des cultures selon la nomenclature CAN
left = df['surface_culture_departementales_agreste']
right = df['match_agreste_can']
df['surface_culture_departementales_agreste_extanded'] = pd.merge(left, right, left_on ='LIB_SAA', right_on='nomenclature_agreste')

# création du dataframe permettant d'effectuer le match entre les départements et les noms des anciennes région
df['match_departement_ancienne_region'] = pd.DataFrame([DICT_MATCH_DEPT_ANCIENNE_REGION]).T.reset_index().rename(columns={
    0:"nom_ancienne_region",
    'index' : "numero_departement"
})

# reclassification des cultures selon la nomenclature CAN
left = df['surface_culture_departementales_agreste_extanded']
right = df['match_departement_ancienne_region']
df['surface_culture_departementales_agreste_extanded'] = pd.merge(left, right, on='numero_departement')

In [ ]:
LAST_DISPONIBLE_YEAR = 2025
YEARS = [k for k in range(2011, LAST_DISPONIBLE_YEAR+1)]

In [ ]:
df['numero_departement_espece_surface'] = pd.melt(
        df['surface_culture_departementales_agreste_extanded'],
        id_vars=['numero_departement', 'nom_ancienne_region', 'nomenclature_can'],
        value_vars=["SURF_"+str(year) for year in YEARS]      
).rename(columns={
    'variable' : 'nom_variable',
    'value' : 'surface'
})
# obtention de la campagne dans un champ int
df['numero_departement_espece_surface']['campagne'] = df['numero_departement_espece_surface']['nom_variable'].str.split('_').apply(lambda x: x[1]).astype(int)
# obtention de la campagne
df['numero_departement_espece_surface']['surface'] = df['numero_departement_espece_surface']['surface'].str.replace(' ', '').fillna(0).astype('int')

# exclusion des "sommes"
df['numero_departement_espece_surface'] = df['numero_departement_espece_surface'].loc[
    (df['numero_departement_espece_surface']['nomenclature_can'] != 'somme') 
    & (df['numero_departement_espece_surface']['nomenclature_can'] != 'null')
]
# calcul des surfaces totales disponibles pour les régions
df['surface_ancienne_region'] = df['numero_departement_espece_surface'].groupby(['nom_ancienne_region', 'campagne']).agg({
    'surface' : 'sum'
})
# groupement 
df['ancienne_region_espece_surface'] = df['numero_departement_espece_surface'].groupby(['nom_ancienne_region', 'campagne', 'nomenclature_can']).agg({
    'surface' : 'sum'
}).reset_index()

# ajout des surfaces totales obtenues
left = df['ancienne_region_espece_surface'] 
right = df['surface_ancienne_region'].rename(columns={'surface' : 'surface_ancienne_region'})
df['ancienne_region_espece_surface_extanded'] = pd.merge(left, right, on=['nom_ancienne_region', 'campagne'])

# calcul du pourcentage de surface pour la culture
df['ancienne_region_espece_surface_extanded']['prc_surface'] = round(df['ancienne_region_espece_surface_extanded']['surface'] / df['ancienne_region_espece_surface_extanded']['surface_ancienne_region'] * 100, 2)

In [ ]:
df['final'] = df['ancienne_region_espece_surface_extanded'].rename(columns={
    'nom_ancienne_region' : 'Nom_Ancienne_Region',
    'campagne' : 'Campagne', 
    'surface':  'Surface_Espece_Region',
    'nomenclature_can' : 'Espece_SSP',
    'surface_ancienne_region' : 'Surface_Region', 
    'prc_surface' : 'Part_surface_espece_region' 
})[[
    'Espece_SSP', 'Campagne', 'Nom_Ancienne_Region', 'Surface_Espece_Region', 'Surface_Region',  'Part_surface_espece_region'
]].sort_values([
    'Campagne', 'Nom_Ancienne_Region', 'Espece_SSP'
])

In [ ]:
df['final']

,Espece_SSP,Campagne,Nom_Ancienne_Region,Surface_Espece_Region,Surface_Region,Part_surface_espece_region
0,Blé dur,2011,Alsace,15,191972,0.01
1,Blé tendre,2011,Alsace,48607,191972,25.32
2,Colza,2011,Alsace,3595,191972,1.87
3,Maïs,2011,Alsace,132489,191972,69.01
4,Orge,2011,Alsace,4740,191972,2.47
...,...,...,...,...,...,...
3235,Maïs,2025,Île-de-France,61151,479521,12.75
3236,Orge,2025,Île-de-France,113841,479521,23.74
3237,Pois protéagineux,2025,Île-de-France,6359,479521,1.33
3238,Tournesol,2025,Île-de-France,7250,479521,1.51
3239,Triticale,2025,Île-de-France,10751,479521,2.24

In [ ]:
df['ancienne_region_espece_surface_extanded_extanded']

KeyError: 'ancienne_region_espece_surface_extanded_extanded'

In [ ]:
df['numero_departement_espece_surface_extanded']

,numero_departement,nom_ancienne_region,nomenclature_can,nom_variable,surface,campagne,surface_totale_region
0,077,Île-de-France,null,SURF_2011,142512,2011,1374263
1,077,Île-de-France,null,SURF_2011,360,2011,1374263
2,077,Île-de-France,Blé tendre,SURF_2011,142872,2011,1374263
3,077,Île-de-France,null,SURF_2011,1340,2011,1374263
4,077,Île-de-France,null,SURF_2011,131,2011,1374263
...,...,...,...,...,...,...,...
59395,974,La Réunion (ancienne région),Pois protéagineux,SURF_2025,0,2025,91
59396,974,La Réunion (ancienne région),null,SURF_2025,0,2025,91
59397,974,La Réunion (ancienne région),null,SURF_2025,0,2025,91
59398,974,La Réunion (ancienne région),null,SURF_2025,0,2025,91
59399,974,La Réunion (ancienne région),null,SURF_2025,2,2025,91