In [117]:
import pandas as pd
from tqdm import tqdm

In [118]:
AGRESTE_PATH = '../../../data/external_data/agreste/'
IFT_PATH = AGRESTE_PATH+'ift/gcpe/'
SURFACE_PATH = AGRESTE_PATH+'surface/'

In [ ]:
# année de la campagne AGRESTE qui recense les IFT moyens par campagne
STUDIED_CAMPAGNES = [
    '2017', 
    '2021'
]

In [119]:
df = {}

df['ift_culture_ancienne_region_gcpe'] = pd.read_csv(IFT_PATH + 'ift_culture_ancienne_region_gcpe.csv')
df['surface_espece_ancienne_region'] = pd.read_csv(SURFACE_PATH + 'surface_espece_ancienne_region.csv')

In [120]:
df['ift_culture_ancienne_region_gcpe']

,nom_ancienne_region,Blé tendre,Blé dur,Triticale,Colza,Tournesol,Pois protéagineux,Maïs fourrage,Maïs grain,Betterave sucrière,Pomme de terre,Canne à sucre,Soja,Lin fibre,Orge de printemps,Orge d'hiver
0,Alsace,3.4,NaN,NaN,NaN,NaN,NaN,NaN,2.8,NaN,NaN,NaN,1.6,NaN,NaN,NaN
1,Aquitaine,3.4,NaN,1.8,NaN,2.7,NaN,2.1,2.9,NaN,11.3,NaN,1.6,NaN,NaN,2.3
2,Auvergne,3.9,NaN,2.6,6.1,2.4,NaN,2.2,3.6,NaN,NaN,NaN,NaN,NaN,NaN,3.5
3,Basse-Normandie,5.3,NaN,3.4,6.8,NaN,5.3,2.3,NaN,NaN,NaN,NaN,NaN,5.8,2.7,4.6
4,Bourgogne,4.4,NaN,2.7,6.7,2.2,3.9,2.4,2.8,NaN,NaN,NaN,2.1,NaN,2.8,4.8
5,Bretagne,4.5,NaN,3.6,3.7,NaN,NaN,2.4,2.6,NaN,16.5,NaN,NaN,NaN,2.4,4.3
6,Centre,5.9,5.7,2.8,6.8,2.9,5.0,2.6,3.4,7.7,13.2,NaN,1.6,NaN,3.8,5.5
7,Champagne-Ardenne,5.4,NaN,2.6,6.5,2.1,4.6,2.6,3.0,7.4,19.6,NaN,1.4,NaN,3.5,5.1
8,Franche-Comté,4.5,NaN,2.8,6.9,NaN,NaN,2.2,2.6,NaN,NaN,NaN,1.8,NaN,NaN,4.3
9,Guadeloupe,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.6,NaN,NaN,NaN,NaN
10,Haute-Normandie,7.0,NaN,NaN,7.1,NaN,5.3,2.3,NaN,7.2,22.6,NaN,NaN,5.6,3.6,6.0
11,Ile-de-France,5.7,NaN,NaN,7.2,NaN,4.0,NaN,3.0,7.3,14.5,NaN,NaN,NaN,3.5,5.3
12,La Réunion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
13,Languedoc-Roussillon,NaN,3.6,0.8,6.6,2.3,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.4
14,Limousin,NaN,NaN,2.1,NaN,NaN,NaN,1.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Lorraine,4.4,NaN,2.8,6.3,2.3,3.0,2.5,2.9,NaN,NaN,NaN,NaN,NaN,2.5,4.5
16,Martinique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN
17,Midi-Pyrénées,3.0,4.5,2.0,4.9,2.4,3.5,1.9,2.8,NaN,NaN,NaN,0.9,NaN,NaN,2.9
18,Nord-Pas-de-Calais,5.7,NaN,NaN,5.9,NaN,5.0,2.2,2.5,6.0,22.4,NaN,NaN,4.5,3.7,5.1
19,Pays de la Loire,4.6,3.7,3.4,5.7,2.2,4.3,2.5,2.8,NaN,NaN,NaN,NaN,NaN,1.9,4.3
20,Picardie,6.0,NaN,NaN,6.6,NaN,4.5,2.5,2.7,6.1,19.1,NaN,NaN,4.7,3.3,5.3
21,Poitou-Charentes,4.7,4.4,2.9,6.7,2.3,4.1,2.3,3.1,NaN,6.6,NaN,1.3,NaN,2.4,4.4
22,Provence-Alpes-Côte d'Azur,NaN,2.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Rhône-Alpes,3.5,2.9,2.1,4.8,2.5,NaN,2.4,3.0,NaN,NaN,NaN,1.4,NaN,NaN,3.3

In [121]:
df['ift_culture_ancienne_region_gcpe'] = df['ift_culture_ancienne_region_gcpe'].melt(
    id_vars="nom_ancienne_region",
    value_vars = list(df['ift_culture_ancienne_region_gcpe'].columns)
).rename(columns={'variable':'culture', 'value':'ift'})

In [122]:
df['surface_espece_ancienne_region']

,Espece_SSP,Campagne,Nom_Ancienne_Region,Surface_Espece_Region,Surface_Region,Part_surface_espece_region
0,Blé dur,2011,Alsace,15,191972,0.01
1,Blé tendre,2011,Alsace,48607,191972,25.32
2,Colza,2011,Alsace,3595,191972,1.87
3,Maïs grain,2011,Alsace,132489,191972,69.01
4,Orge d'hiver,2011,Alsace,4150,191972,2.16
...,...,...,...,...,...,...
3235,Orge d'hiver,2025,Rhône-Alpes,9000,49032,18.36
3236,Orge de printemps,2025,Rhône-Alpes,565,49032,1.15
3237,Pois protéagineux,2025,Rhône-Alpes,105,49032,0.21
3238,Tournesol,2025,Rhône-Alpes,910,49032,1.86
3239,Triticale,2025,Rhône-Alpes,7950,49032,16.21

In [123]:
left = df['ift_culture_ancienne_region_gcpe']
right = df['surface_espece_ancienne_region']
df['ift_culture_ancienne_region_gcpe_extanded'] = pd.merge(left, right, left_on = ['nom_ancienne_region', 'culture'], right_on=['Nom_Ancienne_Region', 'Espece_SSP'], how='left')

In [ ]:
df['surface_espece_ancienne_region'].iloc[]

,Espece_SSP,Campagne,Nom_Ancienne_Region,Surface_Espece_Region,Surface_Region,Part_surface_espece_region
0,Blé dur,2011,Alsace,15,191972,0.01
1,Blé tendre,2011,Alsace,48607,191972,25.32
2,Colza,2011,Alsace,3595,191972,1.87
3,Maïs grain,2011,Alsace,132489,191972,69.01
4,Orge d'hiver,2011,Alsace,4150,191972,2.16
...,...,...,...,...,...,...
3235,Orge d'hiver,2025,Rhône-Alpes,9000,49032,18.36
3236,Orge de printemps,2025,Rhône-Alpes,565,49032,1.15
3237,Pois protéagineux,2025,Rhône-Alpes,105,49032,0.21
3238,Tournesol,2025,Rhône-Alpes,910,49032,1.86
3239,Triticale,2025,Rhône-Alpes,7950,49032,16.21

In [124]:
# on initialise à 0 les valeurs manquantes
df['ift_culture_ancienne_region_gcpe_extanded']['ift'] = df['ift_culture_ancienne_region_gcpe_extanded']['ift'].fillna(0)
df['ift_culture_ancienne_region_gcpe_extanded']['Part_surface_espece_region']  = df['ift_culture_ancienne_region_gcpe_extanded']['Part_surface_espece_region'].fillna(0)

In [ ]:
# creation de l'ift pondéré
df['ift_culture_ancienne_region_gcpe_extanded']['ift_pondere'] = (df['ift_culture_ancienne_region_gcpe_extanded']['ift'] * df['ift_culture_ancienne_region_gcpe_extanded']['Part_surface_espece_region'])/100

Index(['Alsace', 'Aquitaine', 'Auvergne', 'Basse-Normandie', 'Bourgogne',
       'Centre', 'Champagne-Ardenne', 'Franche-Comté', 'Martinique',
       'Guadeloupe', 'Haute-Normandie', 'Ile-de-France', 'La Réunion',
       'Languedoc-Roussillon', 'Limousin', 'Lorraine', 'Picardie',
       'Midi-Pyrénées', 'Nord-Pas-de-Calais', 'Pays de la Loire',
       'Rhône-Alpes', 'Provence-Alpes-Côte d'Azur', 'Bretagne',
       'Poitou-Charentes'],
      dtype='object', name='nom_ancienne_region')